### ISSUE TITLE
.changed? not working as expected in after_save

### ISSUE THREAD

**Issue by Gawyn** [zendesk/property_sets#69]
Building a hook around an Account property I have found some unexpected behaviour. The `changed?` method does not work in the same way for a property than for an attribute in an `after_save` call. An example using one of the properties in `Account`, ip_restriction:

```
class Account
  before_save :print_changes
  after_save :print_changes

  def print_changes
    if name.changed?
      p "Name changed" 
    else
      p "Name NOT changed"
    end

    if texts.detect { |p| p.name == "ip_restriction" }.changed?
     p "IP Restriction changed"
   else
     p "IP Restriction NOT changed"
   end
  end
end

account = Account.last
account.name = "foo"
account.ip_ranges = '1.1.1.1'
account.save
=> "Name changed"
=> "IP Ranges changed"
[Save happens here]
=> "Name changed"
=> "IP Ranges NOT changed"
```

So the behavior is the expected one in `before_save`, but in `after_save` the changes to a property seem to have been committed already. Is that expected or correct somehow? Right now we are using `around_save` to circumvent this issue.

**Comment by srvance** [comment]
We're seeing this same issue with the Classic Rails 5 Upgrade project for channels with the use of `update_attribute`. The update doesn't propagate and get saved because Rails 5 changed the update to check `.changed?`.

**Comment by mariozaizar** [comment]
@Gawyn since you added the original Issue, you know who may be a good candidate to review @saturnflyer's PR (https://github.com/zendesk/property_sets/pull/75) to see if we can get it merged?
