### ISSUE TITLE
Can't create main object and property sets with #create method.

### ISSUE THREAD

**Issue by skatkov** [zendesk/property_sets#76]
I'm trying to adopt your gem for one of my projects, but running into a small "surprise".

I created two models

Store -> client_id:string, name:string,, id:string
StoreSetting -> store_id:string, name:string, value:string

I'm trying to build a store object with one property_set with #create! method.
`Store.create(name: 'test', client: Client.first,  settings: {cname: 'test'})`

But end up with an error:
ActiveRecord::AssociationTypeMismatch: StoreSetting(#47415773112420) expected, got [:cname, "test"] which is an instance of Array(#47415744722620)

I would expect this to work as a regular relation, but it doesn't. Am I doing something wrong here?

**Comment by saturnflyer** [comment]
Try this
```
Store.create(name: 'test', client: Client.first, settings_attributes: [{ name: 'cname', value: 'test'}])
```

**Comment by skatkov** [comment]
Thanks!
